groups:
    - groupa
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_set_preferred_view_style
        - osxdefaults::finder_show_all_files
        - osxdefaults::finder_show_file_extensions
attributes:
    osxdefaults:
        computername: MyComputerName
        finder:
          preferred_view_style: clmv   # column view
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree
