recipes:
  mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
    - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
attributes:
  homebrewalt:
      apps:
          - git
      cask_apps:
          - virtualbox
          - vagrant
